### ISSUE TITLE
Creating FSx for Lustre Data Repository Association: BadRequest: Amazon FSx is unable to validate access to the S3 bucket.

### ISSUE THREAD

**Issue by HanHoRang31** [aws-samples/amazon-eks-machine-learning-with-terraform-and-kubeflow#91] opened 2024-03-20 00:45 UTC
Hello, I am deploying the project, but it seems there is an fsx permission problem. 

> creating FSx for Lustre Data Repository Association: BadRequest: Amazon FSx is unable to validate access to the S3 bucket. Ensure the IAM role or user you are using has s3:Get*, s3:List* and s3:PutObject permissions to the S3 bucket prefix.

How do I solve this? 
My user permission is AdministratorAccess. 
Is there anything else I can add?

**Comment by ajayvohra2005** [comment] 2024-03-20 17:35
Could you please share the Terraform output where you see this error. And also, could you please let me know if the S3 bucket you are using with terraform apply already exists in your account?

**Comment by HanHoRang31** [comment] 2024-03-21 02:14
The following error occurs at line 276 of Main.tf.

> creating FSx for Lustre Data Repository Association: BadRequest: Amazon FSx is unable to validate access to the S3 bucket. Ensure the IAM role or user you are using has s3:Get*, s3:List* and s3:PutObject permissions to the S3 bucket prefix.

The s3 bucket was created in the account. Should I apply terraform without the bucket?

**Comment by ajayvohra2005** [comment] 2024-03-21 03:53
No you must have the S3 bucket created: That part is correct. Can you please tell me if your build machine is an EC2 machine created as per this [documentation](https://github.com/aws-samples/amazon-eks-machine-learning-with-terraform-and-kubeflow/tree/master?tab=readme-ov-file#optional-launch-ec2-instance-for-the-build-machine), or is your build machine a laptop outside EC2? Can you please double check that user/role being used to apply terraform has expected permissions to the S3 bucket.

**Comment by HanHoRang31** [comment] 2024-03-21 04:35
Thank you for your confirmation. My build machine is MAC.
However, regardless of the build machine, my aws configure is an admin user assigned the "AdministratorAccess policy". 
Is a build machine as EC2 necessary?

**Comment by HanHoRang31** [comment] 2024-03-21 09:22
The same problem occurs even when running the boot machine as EC2.
It's the same even though I gave AdministratorAccess role to ec2.
 
│ Error: creating FSx for Lustre Data Repository Association: BadRequest: Amazon FSx is unable to validate access to the S3 bucket. Ensure the IAM role or user you are using has s3:Get*, s3:List* and s3:PutObject permissions to the S3 bucket prefix.
│ 
│   with aws_fsx_data_repository_association.this,
│   on main.tf line 276, in resource "aws_fsx_data_repository_association" "this":
│  276: resource "aws_fsx_data_repository_association" "this" {
│ 
╵

**Comment by ajayvohra2005** [comment] 2024-03-21 17:17
A build machine in EC2 is not required. I have tested using MAC laptop as well, and so far, I am unable to reproduce the error you are seeing. The most likely explanation for your error is that the AWS CLI access keys on your MAC do not have the required permissions to the S3 bucket. You could try creating a new S3 bucket from your MAC using AWS CLI, and that way you will have confirmation that the bucket has the required permissions.

**Comment by HanHoRang31** [comment] 2024-03-22 02:45
Thank you for your opinion. When creating s3, I only set the name and set it to the default options. 
Are there any additional access policies that need to be allowed to s3?

What I still don't understand is that a permission error occurs even though I set my CLI and boot machine Role to AdministratorAccess.

**Comment by ajayvohra2005** [comment] 2024-03-22 18:07
> What I still don't understand is that a permission error occurs even though I set my CLI and boot machine Role to AdministratorAccess.

S3 bucket access depends on user/role permissions accessing the bucket,  but also [Bucket policy](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucket-policies.html) permissions. Administrator Access does not automatically guarantee S3 bucket access.

**Comment by HanHoRang31** [comment] 2024-03-24 11:04
Thanks for letting me know, so can you tell me how to create an s3 bucket and do additional things for access fsx? 
I looked for it but couldn't find it... 
I think it would be good to add it to the readme.

**Comment by ajayvohra2005** [comment] 2024-03-24 16:59
This the general documentation for [Linking an S3 bucket to FSx for Lustre file-system](https://docs.aws.amazon.com/fsx/latest/LustreGuide/create-dra-linked-data-repo.html) using a data repository association.

I just ran following test from my Mac laptop successfully, where I created a new S3 bucket, and then applied terraform:

```
aws s3api create-bucket --region us-west-2 --bucket YOUR_BUCKET_NAME --create-bucket-configuration LocationConstraint=us-west-2

terraform apply -var="profile=default" -var="region=us-west-2" -var="cluster_name=ml-eks-cluster" -var='azs=["us-west-2d","us-west-2b","us-west-2c"]' -var="import_path=s3://YOUR_BUCKET_NAME/ml-platform"
```

**Comment by HanHoRang31** [comment] 2024-03-25 05:35
Ah, I found that. 
The region of my aws provider file was set incorrectly. 
Referring to the document you shared link, fsx and s3 should be in the same place. 
Thanks for letting me know

**Comment by ajayvohra2005** [comment] 2024-03-27 16:04
Issue resolved by user by specifying AWS region.

**Closed by ajayvohra2005** 2024-03-27 16:04 UTC
